### ISSUE TITLE
Log contains some errors

### ISSUE THREAD

**Issue by Horst12** [stnkl/EverythingToolbar#29]
Works fine so far but the log file contains many errrors.
It looks like you have left some code from your environment.
Here the last block:
2020-11-20 19:37:36.4774|INFO|EverythingToolbar started. Version: 0.5.2.0, OS: Microsoft Windows NT 10.0.19042.0|
2020-11-20 19:37:36.6276|ERROR|Theme file not found. Defaulting to 'Medium' theme.|
2020-11-20 19:38:21.6995|INFO|Everything version: 1.4.1|
2020-11-20 19:38:21.8016|ERROR|Failed to get file size.|System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\Microsoft\Windows Defender\Scans\History\Service\Unknown.Log' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.get_Length()
   at EverythingToolbar.Helpers.Utils.GetBytesReadable(String path) in C:\Users\stain\Entwicklung\Windows\EverythingToolbar\EverythingToolbar\Helpers\Utils.cs:line 19
2020-11-20 19:38:21.8405|ERROR|Failed to get file size.|System.UnauthorizedAccessException: Access to the path 'C:\Windows\Prefetch\ReadyBoot\rblayout.xin' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.get_Length()
   at EverythingToolbar.Helpers.Utils.GetBytesReadable(String path) in C:\Users\stain\Entwicklung\Windows\EverythingToolbar\EverythingToolbar\Helpers\Utils.cs:line 19
2020-11-20 19:38:21.8405|ERROR|Failed to get file size.|System.UnauthorizedAccessException: Access to the path 'C:\Windows\Prefetch\SPLWOW64.EXE-B30DB99F.pf' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.get_Length()
   at EverythingToolbar.Helpers.Utils.GetBytesReadable(String path) in C:\Users\stain\Entwicklung\Windows\EverythingToolbar\EverythingToolbar\Helpers\Utils.cs:line 19
2020-11-20 19:38:21.8405|ERROR|Failed to get file size.|System.UnauthorizedAccessException: Access to the path 'C:\Windows\Prefetch\REFLECTMONITOR.EXE-AC29DE95.pf' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.get_Length()
   at EverythingToolbar.Helpers.Utils.GetBytesReadable(String path) in C:\Users\stain\Entwicklung\Windows\EverythingToolbar\EverythingToolbar\Helpers\Utils.cs:line 19
2020-11-20 19:38:22.0273|ERROR|Failed to get file size.|System.UnauthorizedAccessException: Access to the path 'C:\Windows\Prefetch\REFLECTMONITOR.EXE-AC29DE95.pf' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.get_Length()
   at EverythingToolbar.Helpers.Utils.GetBytesReadable(String path) in C:\Users\stain\Entwicklung\Windows\EverythingToolbar\EverythingToolbar\Helpers\Utils.cs:line 19
2020-11-20 19:38:22.0273|ERROR|Failed to get file size.|System.UnauthorizedAccessException: Access to the path 'C:\Windows\Prefetch\REFLECTUI.EXE-5FCE477B.pf' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.get_Length()
   at EverythingToolbar.Helpers.Utils.GetBytesReadable(String path) in C:\Users\stain\Entwicklung\Windows\EverythingToolbar\EverythingToolbar\Helpers\Utils.cs:line 19
2020-11-20 19:38:22.0582|ERROR|Failed to get file size.|System.UnauthorizedAccessException: Access to the path 'C:\Windows\System32\SleepStudy\SleepStudyTraceSession.etl' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.get_Length()
   at EverythingToolbar.Helpers.Utils.GetBytesReadable(String path) in C:\Users\stain\Entwicklung\Windows\EverythingToolbar\EverythingToolbar\Helpers\Utils.cs:line 19
2020-11-20 19:38:43.3287|ERROR|Failed to get file size.|System.UnauthorizedAccessException: Access to the path 'C:\Windows\Prefetch\REFLECTMONITOR.EXE-AC29DE95.pf' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.get_Length()
   at EverythingToolbar.Helpers.Utils.GetBytesReadable(String path) in C:\Users\stain\Entwicklung\Windows\EverythingToolbar\EverythingToolbar\Helpers\Utils.cs:line 19
2020-11-20 19:38:43.3287|ERROR|Failed to get file size.|System.UnauthorizedAccessException: Access to the path 'C:\Windows\Prefetch\REFLECTUI.EXE-5FCE477B.pf' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.get_Length()
   at EverythingToolbar.Helpers.Utils.GetBytesReadable(String path) in C:\Users\stain\Entwicklung\Windows\EverythingToolbar\EverythingToolbar\Helpers\Utils.cs:line 19
2020-11-20 19:41:19.3792|ERROR|Failed to get file size.|System.UnauthorizedAccessException: Access to the path 'C:\Windows\Prefetch\DDVCOLLECTORSVCAPI.EXE-A235C1F8.pf' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.get_Length()
   at EverythingToolbar.Helpers.Utils.GetBytesReadable(String path) in C:\Users\stain\Entwicklung\Windows\EverythingToolbar\EverythingToolbar\Helpers\Utils.cs:line 19
2020-11-20 19:41:19.3792|ERROR|Failed to get file size.|System.UnauthorizedAccessException: Access to the path 'C:\Windows\Prefetch\DDVDATACOLLECTOR.EXE-2D1AA20C.pf' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.get_Length()
   at EverythingToolbar.Helpers.Utils.GetBytesReadable(String path) in C:\Users\stain\Entwicklung\Windows\EverythingToolbar\EverythingToolbar\Helpers\Utils.cs:line 19

**Comment by stnkl** [comment]
Yeah, I should probably not log that every time. The pdb files contain file paths specific to my environment. It makes it easier to debug non-debug releases. It's just that this error was never logged before 0.5.0 (stable).

I will change that for the next release. Thanks for letting me know!
