### ISSUE TITLE
Bug: No longer works in older Windows 10 since v1.0

### ISSUE THREAD

**Issue by Darthagnon** [stnkl/EverythingToolbar#323]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/stnkl/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/stnkl/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.0.1

### Windows Version

Win10 v1709

### Steps to reproduce

1. Install Everything Toolbar v1.0 or higher (last tested working version is v0.7.4)
2. Enable it in the taskbar
3. Explorer will restart and it won't appear.

### Expected Behavior

It used to work.

### Actual Behavior

v0.8.2 beta gives the following exception, rather than failing silently:

```
System.Windows.Markup.XamlParseException: 'Cannot create unknown type '{clr-namespace:EverythingToolbar;assembly=EverythingToolbar}Win10or11Converter'.' Line number '4' and line position '48'. ---> System.Xaml.XamlObjectWriterException: 'Cannot create unknown type '{clr-namespace:EverythingToolbar;assembly=EverythingToolbar}Win10or11Converter'.' Line number '4' and line position '48'.
   at System.Xaml.XamlObjectWriter.WriteStartObject(XamlType xamlType)
   at System.Windows.Markup.WpfXamlLoader.WriteStartObject(XamlReader xamlReader, XamlObjectWriter xamlWriter, XamlContextStack`1 stack)
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, Boolean skipJournaledProperties, Uri baseUri)
   at System.Windows.Markup.XamlReader.Load(XamlReader xamlReader, ParserContext parserContext)
   at System.Windows.Markup.XamlReader.Load(XmlReader reader, ParserContext parserContext, XamlParseMode parseMode, Boolean useRestrictiveXamlReader)
   at System.Windows.Markup.XamlReader.Load(Stream stream, ParserContext parserContext, Boolean useRestrictiveXamlReader)
   at MS.Internal.AppModel.MimeObjectFactory.GetObjectAndCloseStream(Stream s, ContentType contentType, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter)
   at System.Windows.ResourceDictionary.set_Source(Uri value)
   at EverythingToolbar.Helpers.ApplicationResources.AddResource(String type, String name) in C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\Properties\Resources.Designer.cs:line 734
   at EverythingToolbar.Helpers.ApplicationResources.ApplyTheme(String themeName) in C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\Properties\Resources.Designer.cs:line 743
   at EverythingToolbar.Helpers.ApplicationResources.LoadDefaults() in C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\Properties\Resources.Designer.cs:line 725
   at EverythingToolbar.ToolbarControl..ctor() in C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\Data\SearchResult.cs:line 32
   at CSDeskBand.Deskband..ctor() in C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\ShellContextMenu.cs:line 49
```

### Log output

2023-02-02 21:26:03.9333|INFO|CSDeskBand.CSDeskBandWpf|EverythingToolbar Deskband 1.0.0.0 started. OS: Microsoft Windows NT 10.0.16299.0|
2023-02-02 21:26:35.1076|INFO|CSDeskBand.CSDeskBandWpf|EverythingToolbar Deskband 1.0.0.0 started. OS: Microsoft Windows NT 10.0.16299.0|
2023-02-02 21:34:32.8725|INFO|CSDeskBand.CSDeskBandWpf|EverythingToolbar Deskband 1.0.1.0 started. OS: Microsoft Windows NT 10.0.16299.0|
2023-02-02 22:49:40.5061|INFO|CSDeskBand.CSDeskBandWpf|EverythingToolbar Deskband 1.0.1.0 started. OS: Microsoft Windows NT 10.0.16299.0|

**Comment by Darthagnon** [comment]
The "restart PC" prompt added to the installers since v0.8 seems unnecessary, too; v0.7.4 works perfectly without any restart (I don't even need to restart explorer.exe). I suspect it's some part of the Win11 themeing that is incompatible with older versions of Win10 and crashes.

**Comment by stnkl** [comment]
For 1.0 I think you should be able to fix it by creating the `SystemUsesLightTheme` value in registry like this:

![grafik](https://user-images.githubusercontent.com/17520641/216667926-6480b178-71f1-47cf-a5bd-8e07a2730e8b.png)

**Comment by NotesOfReality** [comment]
I'm on W10 1809 (x64) and I can confirm the above-mentioned fix works fine.
I installed the latest version of EverythingToolbar (1.0.1) first without the fix and it made the taskbar unable to start (with desktop window manager being unable to start too), after uninstalling it and then reinstalling it and applying the fix before rebooting things are fine.

**Comment by stnkl** [comment]
@NotesOfReality Thanks for reporting back. The fix is already implemented and I will make a release later this weekend!
