### ISSUE TITLE
Create installer

### ISSUE THREAD

**Issue by Slayr** [stnkl/EverythingToolbar#86]
I own a dell inspiron 13 5000 series, running windows 10 home single language 20H2, 
After i had restarted my laptop, an unhandled exception ocurred (given below)
Other than that, lovin this

System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'EverythingToolbar.SettingsControl' that matches the specified binding constraints threw an exception. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\rishi\Downloads\EverythingToolbar-0.6.1\Themes'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern)
   at EverythingToolbar.Helpers.ResourceLoader..ctor(String folder, String name)
   at EverythingToolbar.SettingsControl..ctor()
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at EverythingToolbar.ToolbarControl..ctor()
   at CSDeskBand.Deskband..ctor()

**Comment by stnkl** [comment]
Did you delete any installation files after installing? You have to keep all the files. It looks like the `Themes` folder can not be found anymore.

**Comment by BinaryAssault** [comment]
@stnkl, maybe you can convert to a clickonce install so the install folder isn't relied on for required files. I can do this at some point and make a pull request if desired.

**Comment by stnkl** [comment]
> @stnkl, maybe you can convert to a clickonce install so the install folder isn't relied on for required files. I can do this at some point and make a pull request if desired.

I actually wanted to read into [Wix](https://wixtoolset.org) this weekend to create a proper installer. I already changed the installation [script](https://github.com/stnkl/EverythingToolbar/blob/master/EverythingToolbar/Inst/install.cmd) to not need admin rights anymore but the program files still have to remain in that folder atm. Do you have experience with Wix?

**Comment by BinaryAssault** [comment]
> > @stnkl, maybe you can convert to a clickonce install so the install folder isn't relied on for required files. I can do this at some point and make a pull request if desired.
> 
> I actually wanted to read into [Wix](https://wixtoolset.org) this weekend to create a proper installer. I already changed the installation [script](https://github.com/stnkl/EverythingToolbar/blob/master/EverythingToolbar/Inst/install.cmd) to not need admin rights anymore but the program files still have to remain in that folder atm. Do you have experience with Wix?

Unfortunately not much. I just discovered this tool (and it's awesome, thanks for that) so I don't know much about it. But since it's a dll and a folder or two, why not just use clickonce and have it put the folders in a user data folder? I personally feel Wix may be too complex for this.

**Comment by stnkl** [comment]
> Unfortunately not much. I just discovered this tool (and it's awesome, thanks for that) so I don't know much about it. But since it's a dll and a folder or two, why not just use clickonce and have it put the folders in a user data folder? I personally feel Wix may be too complex for this.

I actually only just googled "clickonce". Didn't know about that either! But it looks like it can't add registry entries which is needed for EverythingToolbar to run (see the script I linked earlier). I have seen Wix being used by [audio-band](https://github.com/dsafa/audio-band/tree/master/src/AudioBandInstaller) and it doesn't look that hard to implement. It would allow EverythingToolbar to be listed as installed applications which I think would be really nice as well.
